Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Lesson12.Controllers
{
    public class ExerciseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Exercise1()
        {
            return View();
        }

        // TODO Lesson12 Task 1-3 Implement Exercise1 to allow picture upload
        // Use 6P Part1 slides to help you
        [HttpPost]
        public IActionResult Exercise1(IFormFile picture)
        {
            // Implement your code here
            if (picture != null)
            {
                var filePath = Path.Combine(Environment.CurrentDirectory, "wwwroot\\Exercise1\\picture.png");
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    picture.CopyTo(stream);
                }
            }
            else
            {
                TempData["Msg"] = "Failed to upload picture";
            }
            return View();
        }

        public IActionResult Exercise2()
        {
            return View();
        }

        public IActionResult Exercise3()
        {
            return View();
        }

        public IActionResult Exercise4()
        {
            return View();
        }
    }
}

Views/Exercise/Exercise1.cshtml
@{ 
// TODO Lesson12 Task 1-1 Make sure your form's encoding type is "multipart/form-data"
}
<form enctype="multipart/form-data"
      asp-controller="Exercise"
      asp-action="Exercise1"
      class="form-horizontal ">
    <div class="form-group">
        <h3 class="control-label.text-left col-offset-2 col-10">Exercise 1: Upload picture</h3>
        @if (TempData["Msg"] != null)
        {
            <span style="color:red">@TempData["Msg"]</span><br />
        }
    </div>

    <div class="form-group">
        <label class="control-label col-2" for="picture">Picture:</label>
        <div class="col-10">
            @{
                // TODO Lesson12 Task 1-2 Add an file type input element below
                // Make sure the name of the this input element is picture
                // The element should only accept files with extension .png
            }
            <input type="file" class="form-control" id="picture" name="picture" accept=".png">
        </div>
    </div>
    <div class="form-group">
        <div class="col-offset-2 col-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

<div class="col-offset-2 col-10">
    <img src="/exercise1/picture.png" alt="No picture uploaded" />
</div>

Views/Exercise/Exercise2.cshtml
@section ScriptSection {
    <script>

        @{ 
// TODO Lesson12 Task 2-2 Add code to perform ajax call to "/api/Exercise" to upload the form fmPicture
// Refer to 6P Part 1 slides
        }
        function uploadPicture() {
            var form = $("#fmPicture").get(0); // retrieve the HTMLFormElement object
            var fileinput = $("#picture").get(0); // retrieve the HTMLInputElement object
            var formdata = new FormData(form);

            // insert your code here
            $.ajax({
                url: "/api/Exercise",
                type: 'POST',
                data: formdata,
                success: function (data) {
                    if (data == 0) {
                        alert("Picture upload failed!")
                    }
                    else {
                        $("#imgEx2").attr("src", "/Exercise2/" + data)
                    }
                },
                contentType: false,
                processData: false
            });

        }

        $(document).ready(function () {
            $("#btnUploadPic").click(uploadPicture);
        });
    </script>
}
<form enctype="multipart/form-data" id="fmPicture" class="form-horizontal ">
    <div class="form-group">
        <h3 class="control-label.text-left col-offset-2 col-10">Exercise 2: Upload picture through web api</h3>
    </div>

    <div class="form-group">
        <label class="control-label col-2" for="picture">Picture:</label>
        <div class="col-10">
            <input type="file" class="form-control" id="picture" name="picture" accept=".jpg,.png">
        </div>
    </div>
    <div class="form-group">
        <div class="col-offset-2 col-10">
            <button id="btnUploadPic" type="button" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

<div class="col-offset-2 col-10">
    <img id="imgEx2" src="" alt="No picture uploaded" />
</div>

Views/Exercise/Exercise3.cshtml
@section ScriptSection {
    <script src="~/lib/jquery/recorder.js"></script>

    <script>
        var record;
        var stop;
        var gumStream; //stream from getUserMedia()
        var rec; //Recorder.js object
        var input; //MediaStreamAudioSourceNode we'll be recording
        // shim for AudioContext when it's not avb.
        var AudioContext = window.AudioContext || window.webkitAudioContext;
        var audioContext = new AudioContext; //new audio context to help us record

        function createDownloadLink(blob) {

            var url = URL.createObjectURL(blob);
            var link = $("#lnkDownload").get(0);

            //link the a element to the blob
            link.href = url;
            link.download = new Date().toISOString() + '.wav';
            link.innerHTML = link.download;
        }

        function mediaSetup() {
            if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                console.log('getUserMedia supported.');
                navigator.mediaDevices.getUserMedia(
                    // constraints - only audio needed for this app
                    {
                        audio: true
                    })

                    // Success callback
                    .then(function (stream) {
                        /* assign to gumStream for later use */

                        gumStream = stream;

                        /* use the stream */
                        input = audioContext.createMediaStreamSource(stream);

                        /*
                        Create the Recorder object and configure to record mono sound (1 channel)
                        Recording 2 channels  will double the file size
                        */
                        rec = new Recorder(input, { numChannels: 1 })

                        record = $("#btnStart");
                        stop = $("#btnStop");

                        record.click(function () {
                            //start the recording process
			    audioContext.resume();
                            rec.record()
                            record.hide();
                            stop.show();
                        });

                        stop.click(function () {
                            rec.stop();

                            //stop microphone access
                            gumStream.getAudioTracks()[0].stop();

                            //create the wav blob and pass it on to createDownloadLink
                            rec.exportWAV(createDownloadLink);
                            stop.hide();
                            record.show();
                        });
                    })

                    // Error callback
                    .catch(function (err) {
                        console.log('The following getUserMedia error occured: ' + err);
                    }
                    );
            } else {
                console.log('getUserMedia not supported on your browser!');
            }
        }

        $(document).ready(
            function () {
                mediaSetup();
            }
        );
    </script>
}
<form class="form-horizontal">
   <partial name="_SimpleRecorder" />
</form>

Views/Exercise/Exercise4.cshtml
@section ScriptSection {
    <script>
        function uploadWAVFile() {
            var form = $("#fmSound").get(0);
            var fileinput = $("#sound").get(0);
            var formdata = false;
            if (window.FormData) {
                formdata = new FormData(form);
            }

            $.ajax({
                url: "/api/Azure/SpeechToText",
                type: 'POST',
                data: formdata,
                success: function (data) {
                    if (data == 0)
                        alert("WAV file upload failed!")
                    else {
                        $("#taText").val(data);
                    }
                },
                contentType: false,
                processData: false
            });
        }

        $(document).ready(function () {
            $("#btnUploadWAV").click(uploadWAVFile);
        });
    </script>
}
<form enctype="multipart/form-data" id="fmSound" class="form-horizontal ">
    <div class="form-group">
        <h3 class="control-label.text-left col-offset-2 col-10">Exercise 4: Transcribe sound file</h3>
    </div>

    <div class="form-group">
        <label class="control-label col-2" for="sound">WAV file:</label>
        <div class="col-10">
            <input type="file" class="form-control" id="sound" name="sound" accept=".wav">
        </div>
    </div>
    <div class="form-group">
        <div class="col-offset-2 col-10">
            <button id="btnUploadWAV" type="button" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

<div class="col-offset-2 col-10">
    <textarea id="taText" rows="10" cols="100"></textarea>
</div>